.row
  .col-sm-12.col-md-12
    h2 = t "welcome_to_cry_rest"
    p REST API and MVC Starter Kit written in Crystal language.
    .list-group
      a.list-group-item.list-group-item-action target="_blank" href="https://github.com/PetrNikolas/cry_rest" Getting Started with CryRest
      a.list-group-item.list-group-item-action target="_blank" href="https://docs.amberframework.org" Getting Started with Amber Framework
      a.list-group-item.list-group-item-action target="_blank" href="https://github.com/veelenga/awesome-crystal" List of Awesome Crystal projects and shards
      a.list-group-item.list-group-item-action target="_blank" href="https://crystalshards.xyz" What's hot in Crystal right now
